### ISSUE TITLE
can't load the gem

### ISSUE THREAD

**Issue by robsalasco** [theoldreader/feedjira-atypon#1]
Hi! I can't load the gem

```
robsalasco@agafya:~/Dev/rssjournalmaster$ irb
irb(main):001:0> require "feedjira-atypon"
LoadError: cannot load such file -- feedjira-atypon
	from /Users/robsalasco/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/robsalasco/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):1
	from /Users/robsalasco/.rbenv/versions/2.4.1/bin/irb:11:in `<main>'
```

**Comment by robsalasco** [comment]
fixed ;)
